spring:
  application:
    name: greeting-service
server:
  port: 8081
greeting-service:
  greeting: "Ol\u00E1"
  default-value: "Neide"
management:
  endpoints:
    web:
      exposure:
        include:
        - 'mappings'
        - 'refresh'