spring:
  application:
    name: greeting-service
server:
  port: 8081
greeting-service:
  greeting: "tchau"
  default-value: "Mondo"
management:
  endpoints:
    web:
      exposure:
        include:
        - 'mappings'