spring:
  application:
    name: greeting-service
server:
  port: 8081
greeting-service:
  greeting: "Hola"
  default-value: "Mundo"
management:
  endpoints:
    web:
      exposure:
        include: "*"
        #- 'mappings'
        #- 'refresh'